import { FastifyInstance } from 'fastify'
import { z } from 'zod'
import { prisma } from '../lib/prisma'
import { createReadStream } from 'fs'
import { openai } from '../lib/openai'

export async function createTranscription(app: FastifyInstance) {
  app.post('/videos/:videoId/transcription', async (req) => {
    // get id for video
    const paramsSchema = z.object({
      videoId: z.string().uuid(),
    })
    const { videoId } = paramsSchema.parse(req.params)

    // get prompt
    const bodySchema = z.object({
      prompt: z.string(),
    })
    const { prompt } = bodySchema.parse(req.body)

    // get route where save on video
    const video = await prisma.video.findUniqueOrThrow({
      where: {
        id: videoId,
      },
    })
    const videoPath = video.path
    const audioReadStream = createReadStream(videoPath)

    const response = await openai.audio.transcriptions.create({
      file: audioReadStream,
      model: 'whisper-1',
      language: 'pt',
      response_format: 'json',
      temperature: 0,
      prompt,
    })

    const transcription = response.text
    // update audio return with transcription generated by openai
    await prisma.video.update({
      where: {
        id: videoId,
      },
      data: {
        transcription,
      },
    })

    return { transcription }

    // return response.text

    // return {
    //   videoId,
    //   prompt,
    //   videoPath,
    // }
  })
}
